# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: "Lock old issues and pull requests"

on: # yamllint disable-line rule:truthy
    workflow_call:
        inputs:
            target-repo:
                description: "The repo to run this action on. This is to prevent actions from running on forks unless intended."
                required: true
                type: "string"
            issue-inactive-days:
                description: "The number of days before an issue is considered inactive."
                default: "365"
                required: false
                type: "string"

permissions:
    issues: "write"
    pull-requests: "write"

concurrency:
    group: "lock"

jobs:
    lock-closed:
        if: "github.repository == inputs.target-repo"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142" # v2.7.0
              with:
                egress-policy: "audit"

            - uses: "dessant/lock-threads@v5"
              with:
                  issue-inactive-days: "${{ inputs.issue-inactive-days }}"
