# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "set-default-labels"

on: # yamllint disable-line rule:truthy
    workflow_call:
        inputs:
            target-repo:
                description: "The repo to run this action on. This is to prevent actions from running on forks unless intended."
                required: true
                type: "string"
            skip-delete:
                description: "Delete labels that are not in the list"
                default: false
                required: false
                type: "boolean"
            dry-run:
                description: "If enabled, changes will not be applied.",
                default: "${{ github.event_name == 'pull_request' }}"
                required: false
                type: "boolean"
            yaml-file:
                description: "Path to YAML file containing labels definitions.",
                default: ".github/labels.yml"
                required: false
                type: "string"

permissions:
  # Issues and related comments, assignees, labels, and milestones.
  issues: write

jobs:
    set-default-labels:
        if: "github.repository == inputs.target-repo"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v4"
            - uses: "crazy-max/ghaction-github-labeler@de749cf181958193cb7debf1a9c5bb28922f3e1b" # v5.0.0
              with:
                  github-token: "${{ secrets.GITHUB_TOKEN }}"
                  yaml-file: "${{ inputs.yaml-file }}"
                  dry-run: "${{ inputs.dry-run }}"
                  skip-delete: "${{ inputs.skip-delete }}"
