## more info https://github.com/crazy-max/ghaction-github-labeler

- name: "s: needs decision"
  description: "Needs team/maintainer decision"
  color: "C453C3"

- name: "s: needs proposal"
  description: "Changelog Fixed"
  color: "fbca04"

- name: "s: needs design"
  description: "Changelog Fixed"
  color: "fbca04"

- name: "s: accepted"
  description: "Accepted feature / Confirmed bug"
  color: "0E8A16"

- name: "s: awaiting more info"
  description: "Additional information are requested"
  color: "B76026"

- name: "s: invalid"
  description: "This doesn't seem right"
  color: "E4E669"

- name: "s: on hold"
  description: "Blocked by something or frozen to avoid conflicts"
  color: "A03F0B"

- name: "s: pending triage"
  description: "Pending Triage"
  color: "dddddd"

- name: "s: waiting for user interest"
  description: "Waiting for more users interested in this feature"
  color: "4B02CE"

- name: "s: wontfix"
  description: "This will not be worked on"
  color: "ffffff"

- name: "question"
  description: "Further information is requested"
  color: "956692"

- name: "p: 1-normal"
  description: "Nothing urgent"
  color: "BFDADC"

- name: "p: 2-high"
  description: "Fix main branch"
  color: "FF4d4d"

- name: "p: 3-urgent"
  description: "Fix and release ASAP"
  color: "FF0000"

- name: "needs test"
  description: "More tests are needed"
  color: "FAF1A2"

- name: "needs rebase"
  description: "There is a merge conflict"
  color: "32345B"

- name: "c: bug"
  description: "Something isn't working"
  color: "FFA500"

- name: "c: chore"
  description: "PR that doesn't affect the runtime behavior"
  color: "40E0D0"

- name: "c: docs"
  description: "Improvements or additions to documentation"
  color: "FFFF00"

- name: "c: dependencies"
  description: "Pull requests that adds/updates a dependency"
  color: "AFEEEE"

- name: "c: feature"
  description: "Request for new feature"
  color: "2878FF"

- name: "c: infra"
  description: "Changes to our infrastructure or project setup"
  color: "2c3e50"

- name: "c: refactor"
  description: "PR that affects the runtime behavior, but doesn't add new features or fixes bugs"
  color: "40E0D0"

- name: "c: security"
  description: "Indicates a vulnarability"
  color: "B60205"

- name: "deprecation"
  description: "A deprecation was made in the PR"
  color: "C5DEF5"

- name: "do NOT merge yet"
  description: "Do not merge this PR into the target branch yet"
  color: "FF0205"

- name: "duplicate"
  description: "Duplicate of another issue/PR"
  color: "fef2c0"

- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"

- name: "has workaround"
  description: "Workaround provided or linked"
  color: "4049AD"

- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"

- name: "breaking change"
  description: "Cannot be merged when next version is not a major release"
  color: "B05D08"
