# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Greetings"

on: ["pull_request", "issues"] # yamllint disable-line rule:truthy

permissions:
    contents: "read"

jobs:
    greeting:
        permissions:
            issues: "write" # for actions/first-interaction to comment on first issue
            pull-requests: "write" # for actions/first-interaction to comment on first PR
        runs-on: "ubuntu-latest"

        steps:
            - name: "Harden Runner"
              uses: "step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10" # v2.8.0
              with:
                  egress-policy: "audit"

            - uses: "actions/first-interaction@34f15e814fe48ac9312ccf29db4e74fa767cbab7" # v1.3.0
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  issue-message: "Awesome! Thank you for taking the time to create your first issue! Please review the [guidelines](https://visulima.com/docs/contributing)"
                  pr-message: "Great! Thank you for taking the time to create your first pull request! Please review the [guidelines](https://visulima.com/docs/contributing)"
